sudo: false
matrix:
  include:
    - language: ruby
      cache: bundler
      rvm: 2.5
      before_install:
        - gem update --system
        - gem install bundler -v 2.0.1
        - gem --version
      install:
        - bundle install --with development --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}

    - language: ruby
      cache: bundler
      rvm: 2.6
      before_install:
        - gem update --system
        - gem install bundler -v 2.0.1
        - gem --version
      install:
        - bundle install --with development --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}

    - language: ruby
      cache: bundler
      rvm: rbx-3
      before_install:
        - gem update --system
        - gem install bundler -v 2.0.1
        - gem --version
      install:
        - bundle install --with development --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}

    - language: ruby
      cache: bundler
      rvm: ruby-head
      before_install:
        - gem update --system
        - gem install bundler -v 2.0.1
        - gem --version
      install:
        - bundle install --with development --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}

    - language: node_js
      cache: yarn
      node_js: node

    - language: node_js
      cache: yarn
      node_js: lts/*

  allow_failures:
    - language: ruby
      rvm: ruby-head
    - language: ruby
      rvm: rbx-3
    - language: ruby
      rvm: 2.6
